#!/bin/bash

files=$(ls 0*.patch)

for file in $files; do
  result=""
  num=""
  check=""

  num=$(echo "$file" | cut -d '-' -f 1)
  result=$(ls ${num}* | wc -l)

  [[ "$result" == "1" ]] || {
    check=$(ls -1 ${num}*)
    echo "$file: $num files not only 1: $check"
  exit
  }

	[[ -f /tmp/$file ]] && diff /tmp/$file $file && {
		echo "The same patch /tmp/$file already exists"
		exit
	}
done

echo "git send-email -q --confirm=never --no-signed-off-by-cc --no-chain-reply-to --to=xxx $files"
git send-email	-q \
  --confirm=never \
  --no-signed-off-by-cc \
  --suppress-cc=all \
  --no-chain-reply-to \
  --to="Shuah Khan <skhan@linuxfoundation.org>"\
  --to="linux-kselftest <linux-kselftest@vger.kernel.org>" \
  --to="linux-kernel <linux-kernel@vger.kernel.org>" \
  --cc="Pengfei Xu <pengfei.xu@intel.com>" \
  --cc="Heng Su <heng.su@intel.com>" \
  --cc="Hansen Dave <dave.hansen@intel.com>" \
  --cc="Luck Tony <tony.luck@intel.com>" \
  --cc="Mehta Sohil <sohil.mehta@intel.com>" \
  --cc="Chen Yu C <yu.c.chen@intel.com>" \
  --cc="Andy Lutomirski <luto@kernel.org>" \
  --cc="Borislav Petkov <bp@suse.de>" \
  --cc="Thomas Gleixner <tglx@linutronix.de>" \
  $files

mv -f $files /tmp
