#!/bin/bash

version=""
[[ $1 =~ ^v[1-9]* ]] && {
	version="$1"
	shift
}

repo="linux-drivers-review] [PATCH "

# ${@:--1}, check $2 is -x exist, if no $2, :- will set -1 as default
echo "git format-patch --cover-letter --thread=shallow -M --subject-prefix=\"${repo}${version}\" \"${@:--1}\""
files=$(git format-patch --cover-letter --thread=shallow -M --subject-prefix="${repo}${version}" "${@:--1}")
echo "files:$files"
